### PR TITLE
Modified Readme.md

### PR DESCRIPTION
**Pull request by Rahulkumar2002**
In this , I have added **New Feature** of Hogwarts Website into **Readme.md** file which will help new users to use Hogwarts.

### CODE REVIEW

**Comment by Rahulkumar2002** [comment]
Alright , I will make changes . Should I add this link

 https://github.com/arnav1776/Hogwarts/blob/5b7384d964d980f59373c1688a1df17625885c6b/CONTRIBUTING.mdin

  **Add a link to the contributing guidelines as well.** in this?

**Comment by Rahulkumar2002** [comment]
4houses in one image


Should I use this image to show all 4 houses in one tabular format ?

**Comment by arnav1776** [comment]
@Rahulkumar2002 Use this link https://github.com/arnav1776/Hogwarts/blob/master/CONTRIBUTING.md the one which you have shared shows error on opening. 
And use [this](https://github.com/arnav1776/Hogwarts/pull/70#issuecomment-944940017) it looks good, yes you can remove the house pages just mention there to click on the house logos to know more.

**Comment by Rahulkumar2002** [comment]
> @Rahulkumar2002 Use this link https://github.com/arnav1776/Hogwarts/blob/master/CONTRIBUTING.md the one which you have shared shows error on opening. And use [this](https://github.com/arnav1776/Hogwarts/pull/70#issuecomment-944940017) it looks good, yes you can remove the house pages just mention there to click on the house logos to know more.

ok , I will try my best

**Comment by Rahulkumar2002** [comment]
> https://github.com/Rahulkumar2002/Hogwarts/tree/master#readme

first check it out then , if it is ok then I will make a pull request

**Comment by Rahulkumar2002** [comment]
> Looks great 👍, Thank you for contributing.

More than happy to help

**Pull request merged**
